apiVersion: v1
kind: Secret
metadata:
  name: axoo-track-dynatrace-secrets
type: Opaque
data:
  # echo -n "https://srb94465.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86" | base64
  TENANT_URL: aHR0cHM6Ly9zcmI5NDQ2NS5saXZlLmR5bmF0cmFjZS5jb20vYXBpL3YxL2RlcGxveW1lbnQvaW5zdGFsbGVyL2FnZW50L3VuaXgvZGVmYXVsdC9sYXRlc3Q/YXJjaD14ODY=
  # echo -n "CHANGE_ME_dynatrace_paas_token" | base64
  API_TOKEN: Q0hBTkdFX01FX2R5bmF0cmFjZV9wYWFzX3Rva2Vu

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: axoo-track-dynatrace
  labels:
    app: axoo-track-dynatrace
spec:
  selector:
    matchLabels:
      app: axoo-track-dynatrace
  template:
    metadata:
      labels:
        app: axoo-track-dynatrace
    spec:
      containers:
        - name: oneagent
          image: dynatrace/oneagent:latest
          securityContext:
            privileged: true
          env:
            - name: ONEAGENT_INSTALLER_SCRIPT_URL
              valueFrom:
                secretKeyRef:
                  name: axoo-track-dynatrace-secrets
                  key: TENANT_URL
            - name: ONEAGENT_INSTALLER_DOWNLOAD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: axoo-track-dynatrace-secrets
                  key: API_TOKEN
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: host-root
              mountPath: /mnt/root
              readOnly: true
      hostPID: true
      hostNetwork: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: host-root
          hostPath:
            path: /
