name: 'CI/CD axoo-track - Infrastructure & Déploiement'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # ============================
  # JOB 1 : Validation du code
  # ============================
  validate:
    name: 'Validation Terraform'
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

  # ============================
  # JOB 2 : Déploiement
  # ============================
  deploy:
    name: 'Déploiement sur Minikube'
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
        TF_VAR_dynatrace_token: ${{ secrets.DYNATRACE_TOKEN }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
        TF_VAR_dynatrace_token: ${{ secrets.DYNATRACE_TOKEN }}

    - name: Vérification du déploiement
      run: |
        kubectl get all -n axoo-track
        kubectl get ingress -n axoo-track
